### ISSUE TITLE
how to inference new documents?

### ISSUE THREAD

**Issue by wen-fei** [trangnm58/D3NER#2]
thanks for your nice work!
i want to know how to inference if i have some raw sentences?
 is it supported? or how to transform my raw data to your input format?
If it is convenient, please email me your source code, thank you very much.
my email: qq282699766@gmail.com

**Comment by trangnm58** [comment]
Sorry for the delayed reply!
For inference on the new data using our pre-trained model, all you need to do is changing the "entity_types" file to the list of all your new entity types (one line each).
And then, run:
`python main.pyc <model_name> <dataset> <in_file_path> <out_file_path>`
e.g. `python main.pyc d3ner_cdr cdr data/cdr/cdr_test.txt output.txt`
with "d3ner_cdr" is one of our pre-trained models, "cdr" is the dataset on which that model was trained, "data/cdr/cdr_test.txt" is the sample test file, "output.txt" is just the specified output file. For transforming your raw data, a simple script would do. The format of the input file should be the same as "data/cdr/cdr_test.txt", that is:
```
<id>|t|<text>
<id>|a|<text>
```
For each paragraph, the first line (|t| part) is the title, and the second one (|a| part) is the abstract. This follows the format of BioCreative V. If your data doesn't have <id>, just generate them randomly as they are only used for mapping. If your data doesn't have the title part, just leave the <text> after |t| blank.

However, to best suit your new data and maximize the prediction accuracy, I recommend you train the model using your data. Especially when there are new entity types involved because the given pre-trained models are trained on bio-medical datasets so they can detect, for example, Disease, Chemical, Gene/Proteins, etc. really well but not others. About the source code, I have to ask my professor first. If you have any other problem, feel free to ask me.
